# Generated by Django 3.2.14 on 2022-07-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser_telegram_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='telegram_name',
            new_name='telegram_fullname',
        ),
    ]
